# Workflow's name.
name: Install Packages Workflow
# El evento que dispara el workflow, es este caso un [push] al repositorio.
on: [push]
# Jobs to be executed in the workflow.
jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Instalacion de paquetes
      # apt-get install ...
      # uso de '|' pipe para definir 'scripts' de varias lineas (MULTI-LINE)
      run: |
        echo "Instalando paquetes..."
        echo "Hola, mundo by EEC!" >> hola.txt
        cat hola.txt
    - name: Ejecucion de script.sh
      run: |
        chmod +x script.sh
        ./script.sh
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '14'

    - name: Verify node version
      run: node --version