# Workflow's name.
name: Install Packages Workflow
# El evento que dispara el workflow, es este caso un [push] al repositorio.
on: [push]
# Jobs to be executed in the workflow.
jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
    - name: Instalacion de paquetes
      # apt-get install ...
      # uso de '|' pipe para definir 'scripts' de varias lineas (MULTI-LINE)
      run: |
        echo "Instalando paquetes..."
        echo "Hola, mundo by EEC!" >> hola.txt
        cat hola.txt
    - name: Ejecucion de script.sh
      run: |
        chmod +x script.sh
        ./script.sh
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: latest

    - name: Verify node version
      run: node --version

    # OMITIR [npm install] dado que NO existe el archivo [package.json]
    #- name: Instalacion de dependencias [package.json]
      #run: npm install

    - name: Setup PHP Action [PHP environment]
      uses: shivammathur/setup-php@2.34.1
      with:
        php-version: '8.3'

    - name: Verify PHP version
      run: php --version

    - name: Ejecución de [My custom-eec action]
      # Por convención se usa el nombre del directorio de la acción (GH-Actions busca automáticamente el archivo [action.yml] en el directorio especificado)
      uses: ./.github/actions/custom-action101-eec
      with:
        person-name: "Erick Escamilla C." # Parámetro de entrada definido en [action.yml]
